### ISSUE TITLE
Targeted Sentiment returns blank

### ISSUE THREAD

**Issue by sanpietro** [technekes/alchemy-api-rb#28]
Hello, I have no issues with other endpoints like sentiment analysis and keyword extraction, but when I loop through it shows as blank.

results.each do |data|
    @data = "#{data}"
    @targets = "stranger"
    ts = AlchemyAPI.search(:targeted_sentiment_analysis, text: "#{@data}", targets: "#{@targets}")
    puts ts

  end

**Comment by johnallen3d** [comment]
See #31
