### ISSUE TITLE
Alchemy API Shutting Down

### ISSUE THREAD

**Issue by abhinay** [technekes/alchemy-api-rb#31]
Hi,

I got an email from IBM saying that they are retiring AlchemyAPI. Existing instances will be supported until March 7, 2018, and recommend all AlchemyLanguage users migrate to Watson Natural Language Understanding.

Is there any plan to support Watson Natural Language Understanding?

**Comment by drusepth** [comment]
Voicing some additional interest in this and also subtly subscribing to this thread in case there are any updates.

**Comment by johnallen3d** [comment]
My apologies for the extreme delay in response! Unfortunately we do not plan to add support for Watson Natural Language Understanding at this time. This library was created for our business but never actually used. We shared it and tried to keep up with request but will not be able to undertake the larger efforts.
